# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-09 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BlueOcean', '0002_auto_20170809_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('pricenew', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=20)),
                ('priceold', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=20)),
                ('category', models.CharField(blank=True, default=None, max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='pricenew',
        ),
        migrations.RemoveField(
            model_name='post',
            name='priceold',
        ),
    ]
